spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hrms
      
  profiles:
    active: dev
  
#  cloud:
#    kubernetes:
#      discovery:
#        register: true
#
#      config:
#        enabled: true
#        sources:
#         - namespace: default
#           name: movie-db-config
#        reload:
#         enabled: true
#         mode: polling
#         period: 1000